// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B5871803/app/ent/operative"
	"github.com/B5871803/app/ent/operativerecord"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// OperativeCreate is the builder for creating a Operative entity.
type OperativeCreate struct {
	config
	mutation *OperativeMutation
	hooks    []Hook
}

// SetOperativeType sets the operativeType field.
func (oc *OperativeCreate) SetOperativeType(s string) *OperativeCreate {
	oc.mutation.SetOperativeType(s)
	return oc
}

// SetOperativeName sets the operativeName field.
func (oc *OperativeCreate) SetOperativeName(s string) *OperativeCreate {
	oc.mutation.SetOperativeName(s)
	return oc
}

// AddFromoperativeIDs adds the fromoperative edge to Operativerecord by ids.
func (oc *OperativeCreate) AddFromoperativeIDs(ids ...int) *OperativeCreate {
	oc.mutation.AddFromoperativeIDs(ids...)
	return oc
}

// AddFromoperative adds the fromoperative edges to Operativerecord.
func (oc *OperativeCreate) AddFromoperative(o ...*Operativerecord) *OperativeCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return oc.AddFromoperativeIDs(ids...)
}

// Mutation returns the OperativeMutation object of the builder.
func (oc *OperativeCreate) Mutation() *OperativeMutation {
	return oc.mutation
}

// Save creates the Operative in the database.
func (oc *OperativeCreate) Save(ctx context.Context) (*Operative, error) {
	if _, ok := oc.mutation.OperativeType(); !ok {
		return nil, &ValidationError{Name: "operativeType", err: errors.New("ent: missing required field \"operativeType\"")}
	}
	if v, ok := oc.mutation.OperativeType(); ok {
		if err := operative.OperativeTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "operativeType", err: fmt.Errorf("ent: validator failed for field \"operativeType\": %w", err)}
		}
	}
	if _, ok := oc.mutation.OperativeName(); !ok {
		return nil, &ValidationError{Name: "operativeName", err: errors.New("ent: missing required field \"operativeName\"")}
	}
	if v, ok := oc.mutation.OperativeName(); ok {
		if err := operative.OperativeNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "operativeName", err: fmt.Errorf("ent: validator failed for field \"operativeName\": %w", err)}
		}
	}
	var (
		err  error
		node *Operative
	)
	if len(oc.hooks) == 0 {
		node, err = oc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OperativeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			oc.mutation = mutation
			node, err = oc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(oc.hooks) - 1; i >= 0; i-- {
			mut = oc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OperativeCreate) SaveX(ctx context.Context) *Operative {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (oc *OperativeCreate) sqlSave(ctx context.Context) (*Operative, error) {
	o, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	o.ID = int(id)
	return o, nil
}

func (oc *OperativeCreate) createSpec() (*Operative, *sqlgraph.CreateSpec) {
	var (
		o     = &Operative{config: oc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: operative.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: operative.FieldID,
			},
		}
	)
	if value, ok := oc.mutation.OperativeType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: operative.FieldOperativeType,
		})
		o.OperativeType = value
	}
	if value, ok := oc.mutation.OperativeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: operative.FieldOperativeName,
		})
		o.OperativeName = value
	}
	if nodes := oc.mutation.FromoperativeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   operative.FromoperativeTable,
			Columns: []string{operative.FromoperativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operativerecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return o, _spec
}
