// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/B5871803/app/ent/examinationroom"
	"github.com/B5871803/app/ent/nurse"
	"github.com/B5871803/app/ent/operative"
	"github.com/B5871803/app/ent/operativerecord"
	"github.com/B5871803/app/ent/schema"
	"github.com/B5871803/app/ent/tool"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	examinationroomFields := schema.Examinationroom{}.Fields()
	_ = examinationroomFields
	// examinationroomDescExaminationroomName is the schema descriptor for examinationroomName field.
	examinationroomDescExaminationroomName := examinationroomFields[0].Descriptor()
	// examinationroom.ExaminationroomNameValidator is a validator for the "examinationroomName" field. It is called by the builders before save.
	examinationroom.ExaminationroomNameValidator = examinationroomDescExaminationroomName.Validators[0].(func(string) error)
	nurseFields := schema.Nurse{}.Fields()
	_ = nurseFields
	// nurseDescNurseName is the schema descriptor for nurse_name field.
	nurseDescNurseName := nurseFields[0].Descriptor()
	// nurse.NurseNameValidator is a validator for the "nurse_name" field. It is called by the builders before save.
	nurse.NurseNameValidator = nurseDescNurseName.Validators[0].(func(string) error)
	// nurseDescNurseEmail is the schema descriptor for nurse_email field.
	nurseDescNurseEmail := nurseFields[1].Descriptor()
	// nurse.NurseEmailValidator is a validator for the "nurse_email" field. It is called by the builders before save.
	nurse.NurseEmailValidator = nurseDescNurseEmail.Validators[0].(func(string) error)
	// nurseDescNursePassword is the schema descriptor for nurse_password field.
	nurseDescNursePassword := nurseFields[2].Descriptor()
	// nurse.NursePasswordValidator is a validator for the "nurse_password" field. It is called by the builders before save.
	nurse.NursePasswordValidator = nurseDescNursePassword.Validators[0].(func(string) error)
	// nurseDescNurseTel is the schema descriptor for nurse_tel field.
	nurseDescNurseTel := nurseFields[3].Descriptor()
	// nurse.NurseTelValidator is a validator for the "nurse_tel" field. It is called by the builders before save.
	nurse.NurseTelValidator = nurseDescNurseTel.Validators[0].(func(string) error)
	operativeFields := schema.Operative{}.Fields()
	_ = operativeFields
	// operativeDescOperativeType is the schema descriptor for operativeType field.
	operativeDescOperativeType := operativeFields[0].Descriptor()
	// operative.OperativeTypeValidator is a validator for the "operativeType" field. It is called by the builders before save.
	operative.OperativeTypeValidator = operativeDescOperativeType.Validators[0].(func(string) error)
	// operativeDescOperativeName is the schema descriptor for operativeName field.
	operativeDescOperativeName := operativeFields[1].Descriptor()
	// operative.OperativeNameValidator is a validator for the "operativeName" field. It is called by the builders before save.
	operative.OperativeNameValidator = operativeDescOperativeName.Validators[0].(func(string) error)
	operativerecordFields := schema.Operativerecord{}.Fields()
	_ = operativerecordFields
	// operativerecordDescOperativeTime is the schema descriptor for OperativeTime field.
	operativerecordDescOperativeTime := operativerecordFields[0].Descriptor()
	// operativerecord.DefaultOperativeTime holds the default value on creation for the OperativeTime field.
	operativerecord.DefaultOperativeTime = operativerecordDescOperativeTime.Default.(func() time.Time)
	toolFields := schema.Tool{}.Fields()
	_ = toolFields
	// toolDescToolName is the schema descriptor for toolName field.
	toolDescToolName := toolFields[0].Descriptor()
	// tool.ToolNameValidator is a validator for the "toolName" field. It is called by the builders before save.
	tool.ToolNameValidator = toolDescToolName.Validators[0].(func(string) error)
	// toolDescAmount is the schema descriptor for amount field.
	toolDescAmount := toolFields[1].Descriptor()
	// tool.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	tool.AmountValidator = toolDescAmount.Validators[0].(func(string) error)
}
