// Code generated by entc, DO NOT EDIT.

package examinationroom

const (
	// Label holds the string label denoting the examinationroom type in the database.
	Label = "examinationroom"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExaminationroomName holds the string denoting the examinationroomname field in the database.
	FieldExaminationroomName = "examinationroom_name"

	// EdgeFromexaminationroom holds the string denoting the fromexaminationroom edge name in mutations.
	EdgeFromexaminationroom = "fromexaminationroom"

	// Table holds the table name of the examinationroom in the database.
	Table = "examinationrooms"
	// FromexaminationroomTable is the table the holds the fromexaminationroom relation/edge.
	FromexaminationroomTable = "operativerecords"
	// FromexaminationroomInverseTable is the table name for the Operativerecord entity.
	// It exists in this package in order to avoid circular dependency with the "operativerecord" package.
	FromexaminationroomInverseTable = "operativerecords"
	// FromexaminationroomColumn is the table column denoting the fromexaminationroom relation/edge.
	FromexaminationroomColumn = "examinationroom_id"
)

// Columns holds all SQL columns for examinationroom fields.
var Columns = []string{
	FieldID,
	FieldExaminationroomName,
}

var (
	// ExaminationroomNameValidator is a validator for the "examinationroomName" field. It is called by the builders before save.
	ExaminationroomNameValidator func(string) error
)
