// Code generated by entc, DO NOT EDIT.

package examinationroom

import (
	"github.com/B5871803/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ExaminationroomName applies equality check predicate on the "examinationroomName" field. It's identical to ExaminationroomNameEQ.
func ExaminationroomName(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameEQ applies the EQ predicate on the "examinationroomName" field.
func ExaminationroomNameEQ(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameNEQ applies the NEQ predicate on the "examinationroomName" field.
func ExaminationroomNameNEQ(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameIn applies the In predicate on the "examinationroomName" field.
func ExaminationroomNameIn(vs ...string) predicate.Examinationroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Examinationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExaminationroomName), v...))
	})
}

// ExaminationroomNameNotIn applies the NotIn predicate on the "examinationroomName" field.
func ExaminationroomNameNotIn(vs ...string) predicate.Examinationroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Examinationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExaminationroomName), v...))
	})
}

// ExaminationroomNameGT applies the GT predicate on the "examinationroomName" field.
func ExaminationroomNameGT(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameGTE applies the GTE predicate on the "examinationroomName" field.
func ExaminationroomNameGTE(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameLT applies the LT predicate on the "examinationroomName" field.
func ExaminationroomNameLT(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameLTE applies the LTE predicate on the "examinationroomName" field.
func ExaminationroomNameLTE(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameContains applies the Contains predicate on the "examinationroomName" field.
func ExaminationroomNameContains(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameHasPrefix applies the HasPrefix predicate on the "examinationroomName" field.
func ExaminationroomNameHasPrefix(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameHasSuffix applies the HasSuffix predicate on the "examinationroomName" field.
func ExaminationroomNameHasSuffix(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameEqualFold applies the EqualFold predicate on the "examinationroomName" field.
func ExaminationroomNameEqualFold(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldExaminationroomName), v))
	})
}

// ExaminationroomNameContainsFold applies the ContainsFold predicate on the "examinationroomName" field.
func ExaminationroomNameContainsFold(v string) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldExaminationroomName), v))
	})
}

// HasFromexaminationroom applies the HasEdge predicate on the "fromexaminationroom" edge.
func HasFromexaminationroom() predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromexaminationroomTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromexaminationroomTable, FromexaminationroomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromexaminationroomWith applies the HasEdge predicate on the "fromexaminationroom" edge with a given conditions (other predicates).
func HasFromexaminationroomWith(preds ...predicate.Operativerecord) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromexaminationroomInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromexaminationroomTable, FromexaminationroomColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Examinationroom) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Examinationroom) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Examinationroom) predicate.Examinationroom {
	return predicate.Examinationroom(func(s *sql.Selector) {
		p(s.Not())
	})
}
