// Code generated by entc, DO NOT EDIT.

package tool

const (
	// Label holds the string label denoting the tool type in the database.
	Label = "tool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldToolName holds the string denoting the toolname field in the database.
	FieldToolName = "tool_name"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"

	// EdgeFromtool holds the string denoting the fromtool edge name in mutations.
	EdgeFromtool = "fromtool"

	// Table holds the table name of the tool in the database.
	Table = "tools"
	// FromtoolTable is the table the holds the fromtool relation/edge.
	FromtoolTable = "operativerecords"
	// FromtoolInverseTable is the table name for the Operativerecord entity.
	// It exists in this package in order to avoid circular dependency with the "operativerecord" package.
	FromtoolInverseTable = "operativerecords"
	// FromtoolColumn is the table column denoting the fromtool relation/edge.
	FromtoolColumn = "tool_name"
)

// Columns holds all SQL columns for tool fields.
var Columns = []string{
	FieldID,
	FieldToolName,
	FieldAmount,
}

var (
	// ToolNameValidator is a validator for the "toolName" field. It is called by the builders before save.
	ToolNameValidator func(string) error
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(string) error
)
