// Code generated by entc, DO NOT EDIT.

package tool

import (
	"github.com/B5871803/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ToolName applies equality check predicate on the "toolName" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldToolName), v))
	})
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), v))
	})
}

// ToolNameEQ applies the EQ predicate on the "toolName" field.
func ToolNameEQ(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldToolName), v))
	})
}

// ToolNameNEQ applies the NEQ predicate on the "toolName" field.
func ToolNameNEQ(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldToolName), v))
	})
}

// ToolNameIn applies the In predicate on the "toolName" field.
func ToolNameIn(vs ...string) predicate.Tool {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tool(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldToolName), v...))
	})
}

// ToolNameNotIn applies the NotIn predicate on the "toolName" field.
func ToolNameNotIn(vs ...string) predicate.Tool {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tool(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldToolName), v...))
	})
}

// ToolNameGT applies the GT predicate on the "toolName" field.
func ToolNameGT(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldToolName), v))
	})
}

// ToolNameGTE applies the GTE predicate on the "toolName" field.
func ToolNameGTE(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldToolName), v))
	})
}

// ToolNameLT applies the LT predicate on the "toolName" field.
func ToolNameLT(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldToolName), v))
	})
}

// ToolNameLTE applies the LTE predicate on the "toolName" field.
func ToolNameLTE(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldToolName), v))
	})
}

// ToolNameContains applies the Contains predicate on the "toolName" field.
func ToolNameContains(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldToolName), v))
	})
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "toolName" field.
func ToolNameHasPrefix(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldToolName), v))
	})
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "toolName" field.
func ToolNameHasSuffix(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldToolName), v))
	})
}

// ToolNameEqualFold applies the EqualFold predicate on the "toolName" field.
func ToolNameEqualFold(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldToolName), v))
	})
}

// ToolNameContainsFold applies the ContainsFold predicate on the "toolName" field.
func ToolNameContainsFold(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldToolName), v))
	})
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), v))
	})
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAmount), v))
	})
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.Tool {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tool(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAmount), v...))
	})
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.Tool {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tool(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAmount), v...))
	})
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAmount), v))
	})
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAmount), v))
	})
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAmount), v))
	})
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAmount), v))
	})
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAmount), v))
	})
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAmount), v))
	})
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAmount), v))
	})
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAmount), v))
	})
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAmount), v))
	})
}

// HasFromtool applies the HasEdge predicate on the "fromtool" edge.
func HasFromtool() predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromtoolTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromtoolTable, FromtoolColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromtoolWith applies the HasEdge predicate on the "fromtool" edge with a given conditions (other predicates).
func HasFromtoolWith(preds ...predicate.Operativerecord) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromtoolInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromtoolTable, FromtoolColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Tool) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Tool) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tool) predicate.Tool {
	return predicate.Tool(func(s *sql.Selector) {
		p(s.Not())
	})
}
