/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOperativerecord,
    EntOperativerecordFromJSON,
    EntOperativerecordFromJSONTyped,
    EntOperativerecordToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntToolEdges
 */
export interface EntToolEdges {
    /**
     * Fromtool holds the value of the fromtool edge.
     * @type {Array<EntOperativerecord>}
     * @memberof EntToolEdges
     */
    fromtool?: Array<EntOperativerecord>;
}

export function EntToolEdgesFromJSON(json: any): EntToolEdges {
    return EntToolEdgesFromJSONTyped(json, false);
}

export function EntToolEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntToolEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromtool': !exists(json, 'fromtool') ? undefined : ((json['fromtool'] as Array<any>).map(EntOperativerecordFromJSON)),
    };
}

export function EntToolEdgesToJSON(value?: EntToolEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fromtool': value.fromtool === undefined ? undefined : ((value.fromtool as Array<any>).map(EntOperativerecordToJSON)),
    };
}


